categories={
    "ACCESSOIRES GÉNÉRAUX": [
        "ACC / Accessoires autos",
        "ACC / AMENAGEMENT",
        "ACC / CASQUES",
        "ACC / DIVERS",
    ],
    "ACCESSOIRES AUTO":[
        "ACC / KIT AUTO",
    ],
    "ACCESSOIRES MOTO":[
        "ACC / KIT MOTO",
        "ACC / KIT MOTO / TC45L",
        "ACC / KIT MOTO / TC50L",
        "ACC / EQUIPEMENT MOTO",
        "ACC / MOTO",
        "ACC / Moto",
    ],
    "PIECES MOTO":[
        "ACC / DIVERSES PIECES MOTOS",
        "ACC / Diverses Pièces Motos - 2",
        "ACC / MOTO / KRROUTIERE",
        "ACC / MOTO / LFCROSS",
        "ACC / MOTO / LFROUTIERE",
        "ACC / MOTO / LFSCOOTER",
        "ACC / MOTO / PCROSS",
        "ACC / MOTO / PCROUTIERE",
        "ACC / MOTO / PCTRIC",
        "ACC / MOTO / POCKET BIKE",
        "ACC / MOTO / ROADSTER",
        "ACC / MOTO / SCRAMBLER",
        "ACC / MOTO / SPORTIVE",
        "ACC / MOTO / SUPER MOTARD",
        "ACC / MOTO-",
        "ACC / PICK UP & QUAD / SSV",
    ],
    "PNEUMATIQUES & JANTES": [
        "ACC / PNEUMOTOS",
        "ACC / PNEUSMOTO",
        "ACC / JANTE  / 13\"",
        "ACC / JANTE  / 14\"",
        "ACC / JANTE  / 15\"",
        "ACC / JANTE  / 16\"",
        "ACC / JANTE  / 17\"",
        "Industrie / Pneumatique",
        "AUTOMOTIVE / PNEU",
        "AUTOMOTIVE / CHAMBRE A AIR"
    ],
    "BATTERIE":[
        "ACC / BATTERIE",
        "ACC / BATTERIE / BT3A",
        "ACC / BATTERIE / BT7A",
    ],
    "PIÈCES DÉTACHÉES": [
        "PDR",
        "PDR / AT",
        "PDR / BAIC",
        "PDR / BAW",
        "PDR / BYD",
        "PDR / CAMC",
        "PDR / CHERRY",
        "PDR / ENRANGER",
        "PDR / FORLAND",
        "PDR / GENERIQUE",
        "PDR / GRAND TIGER",
        "PDR / HIGER",
        "PDR / HOWO",
        "PDR / HUMMER",
        "PDR / HYUNDAI",
        "PDR / Isuzu 4x4",
        "PDR / Isuzu Berline",
        "PDR / ISUZU CAMION",
        "PDR / ISUZU WFR/BL/MR/BE",
        "PDR / JETTA",
        "PDR / JIAN YE",
        "PDR / JINBEI",
        "PDR / KAMA",
        "PDR / KEYTON",
        "PDR / LOVOL",
        "PDR / OSRAM",
        "PDR / SAMSUNG CAMIONS",
        "PDR / SHACMAN",
        "PDR / SHINERAY",
        "PDR / SINOTRUCK",
        "PDR / TUNLAND PU",
        "PDR / WULING",
        "PDR / YANGZI",
        "ACC / MOTEURCOMPRESSEUR",
        "ACC / ECHAPPEMENT",
        "ACC / Pièces Compresseurs",
        "ACC / Pièces HISUN",
        "ACC / Pièces Moteur 1P52QMI",
        "ACC / Pièces Moteur 1P57QMI",
        "ACC / PIECES DETACHEES / PDBENELLI",
        "ACC / PIECES DETACHEES / PDBAJAJ",
        "ACC / PIECES DETACHEES / PDBX250",
        "ACC / PIECES DETACHEES / PDLeoncino500",
        "ACC / PIECES DETACHEES / PDPIAGGIO",
        "ACC / PIECES DETACHEES / PDRK150E",
        "ACC / PIECES DETACHEES / PDTNT135",
        "ACC / PIECES DETACHEES / PDTNT25",
        "ACC / PIECES DETACHEES / PDTNT300",
        "ACC / PIECES DETACHEES / PDTNT600",
        "ACC / PIECES DETACHEES / PDTNT600i",
        "ACC / PIECES DETACHEES / PDTRK502",
        "ACC / PIECES DETACHEES / PDTVS",
        "ACC / PIECES DETACHEES-",
        "ACC / PIECES DETACHEES- / PD156FMI-2",
        "ACC / PIECES DETACHEES- / PD162FMJ",
        "ACC / PIECES DETACHEES- / PD163FML-2",
        "ACC / PIECES DETACHEES- / PD167MM-M",
        "ACC / PIECES DETACHEES- / PD172MM-2D",
        "ACC / PIECES DETACHEES- / PD173FMM",
        "ACC / PIECES DETACHEES- / PD1P39QMB",
        "ACC / PIECES DETACHEES- / PD1P50FMG-2",
        "ACC / PIECES DETACHEES- / PD1P50FMG-C",
        "ACC / PIECES DETACHEES- / PD1P52FMC-H",
        "ACC / PIECES DETACHEES- / PD1P52FMI-C",
        "ACC / PIECES DETACHEES- / PD1P52QMB",
        "ACC / PIECES DETACHEES- / PD1P52QMI",
        "ACC / PIECES DETACHEES- / PD1P57QMI",
        "ACC / PIECES DETACHEES- / PD2V68FMQ",
        "ACC / PIECES DETACHEES- / PDCARGO210",
        "ACC / PIECES DETACHEES- / PDdirt150",
        "ACC / PIECES DETACHEES- / PDHS1000UTV",
        "ACC / PIECES DETACHEES- / PDHS250UTV",
        "ACC / PIECES DETACHEES- / PDHS350ATV",
        "ACC / PIECES DETACHEES- / PDHS400ATV",
        "ACC / PIECES DETACHEES- / PDHS400UTV",
        "ACC / PIECES DETACHEES- / PDHS500ATV",
        "ACC / PIECES DETACHEES- / PDHS800UTV",
        "ACC / PIECES DETACHEES- / PDLF100-A",
        "ACC / PIECES DETACHEES- / PDLF100-D",
        "ACC / PIECES DETACHEES- / PDLF100D",
        "ACC / PIECES DETACHEES- / PDLF110-7A",
        "ACC / PIECES DETACHEES- / PDLF125-26H",
        "ACC / PIECES DETACHEES- / PDLF125-3",
        "ACC / PIECES DETACHEES- / PDLF125-5",
        "ACC / PIECES DETACHEES- / PDLF125-7",
        "ACC / PIECES DETACHEES- / PDLF125GY",
        "ACC / PIECES DETACHEES- / PDLF125T-26",
        "ACC / PIECES DETACHEES- / PDLF125T-6",
        "ACC / PIECES DETACHEES- / PDLF125T-9R",
        "ACC / PIECES DETACHEES- / PDLF150-13",
        "ACC / PIECES DETACHEES- / PDLF150-15",
        "ACC / PIECES DETACHEES- / PDLF150-16",
        "ACC / PIECES DETACHEES- / PDLF150-17",
        "ACC / PIECES DETACHEES- / PDLF150-3",
        "ACC / PIECES DETACHEES- / PDLF150GY-3A",
        "ACC / PIECES DETACHEES- / PDLF150QT-26",
        "ACC / PIECES DETACHEES- / PDLF150T-12",
        "ACC / PIECES DETACHEES- / PDLF150T-2C",
        "ACC / PIECES DETACHEES- / PDLF200GY-5",
        "ACC / PIECES DETACHEES- / PDLF250GY-2",
        "ACC / PIECES DETACHEES- / PDLF250GY-6",
        "ACC / PIECES DETACHEES- / PDLF400",
        "ACC / PIECES DETACHEES- / PDPC125GY",
        "ACC / PIECES DETACHEES- / PDPC150GY-11",
        "ACC / PIECES DETACHEES- / PDPC200GY-2",
        "ACC / PIECES DETACHEES- / PDPC50-12",
        "ACC / PIECES DETACHEES- / PDPC50-3",
        "AUTOMOTIVE / AMORTISSEUR",
        "AUTOMOTIVE / BOBINE D'ALLUMAGE",
        "AUTOMOTIVE / BOUGIE",
        "AUTOMOTIVE / BUTEE",
        "AUTOMOTIVE / CAPTEUR",
        "AUTOMOTIVE / FILTRE / AIR",
        "AUTOMOTIVE / FILTRE / CARBURANT",
        "AUTOMOTIVE / FILTRE / HUILE",
        "AUTOMOTIVE / GALET",
        "AUTOMOTIVE / KIT",
        "AUTOMOTIVE / PLAQUETTE DE FREIN",
        "AUTOMOTIVE / RESSORT",
        "AUTOMOTIVE / ROULEMENT",
        "AUTOMOTIVE / CARROSSERIES / EXTERIEUR CABINE / VITRE PORTIERE",
        "AUTOMOTIVE / LIAISON AU SOL / SUSPENSION / TRAIN / ESSIEUX ",
        "AUTOMOTIVE / ORGANE / PIECES MOTEUR EMISSION / LUBRIFIANTS"
    ],
    "ACCESOIRES VELO":[
        "ACC / VELO", 
    ],
    "VÉHICULES": [
        "VEH",
        "VEH / BUS / DIESEL",
        "VEH / CAMION  / DIESEL",
        "VEH / CAMION PLATEAU / DIESEL",
        "VEH / REMORQUE / 13.5 m",
        "VEH / SUV",
        "VEH / TRACTEUR ROUTIER",
        "Vehicule CA",
        "Véhicules Occasions"
    ],
    "OUTILLAGE & MATÉRIEL DE GARAGE": [
        "ACC / COMPRESSEURS",
        "ACC / COMPRESSEURS / CP100L",
        "ACC / COMPRESSEURS / CP150L",
        "ACC / COMPRESSEURS / CP200L",
        "ACC / COMPRESSEURS / CP25L",
        "ACC / COMPRESSEURS / CP270L",
        "ACC / COMPRESSEURS / CP500L",
        "ACC / COMPRESSEURS / CP50L",
        "ACC / COMPRESSEURS / CP6L",
        "ACC / ELECTROPORTATIFS",
        "ACC / ELEVATEUR FOG",
        "ACC / Elevateur FOG",
        "ACC / MATERIEL DE GARAGE",
        "ACC / MATERIEL DE GARAGE-",
        "ACC / MATERIEL DE GARAGE- / COMMARIA",
        "ACC / OUTILLAGES",
        "ACC / OUTILLAGES-",
        "Garage",
        "Garage / Consommable",
        "Garage / Peinture"
    ],
    "LUBRIFIANTS": [
        "LUB",
        "AUTOMOTIVE / HUILE",
        "Industrie / Lubrifiants",
        "Industrie / Lubrifiants / Auto Moto",
        "Industrie / Lubrifiants / Engin",
        "Industrie / Lubrifiants / Graisse",
        "Industrie / Lubrifiants / Industriel",
        "Industrie / Lubrifiants / Multi Usage"
    ],
    "MATÉRIAUX DE CONSTRUCTION": [
        "DMC / A CLASSER",
        "DMC / BAKELISE",
        "DMC / BITUME",
        "DMC / BOBINE",
        "DMC / BUSE",
        "DMC / CARREAUX",
        "DMC / CIMENT",
        "DMC / DECLASSER",
        "DMC / ELECTRODE",
        "DMC / FABRICATION / BAC",
        "DMC / FABRICATION / BAC / PRELAQUEE",
        "DMC / FABRICATION / FAITIERE",
        "DMC / FABRICATION / ONDULEE",
        "DMC / FABRICATION / PANNES C",
        "DMC / FABRICATION / PANNES OMEGA",
        "DMC / FER / CARRE",
        "DMC / FER / CORNIERE",
        "DMC / FER / PLAT",
        "DMC / FER / ROND LISSE",
        "DMC / FER / T",
        "DMC / FER / TOR / BARRE DROITE",
        "DMC / FER / TOR / BARRE PLIEE",
        "DMC / FER / UAC",
        "DMC / FILS",
        "DMC / GABION",
        "DMC / GEOTEXTILE",
        "DMC / POUTRELLE / HEA",
        "DMC / POUTRELLE / IPE",
        "DMC / POUTRELLE / IPN",
        "DMC / POUTRELLE / UPN",
        "DMC / TOLE / ONDULEE",
        "DMC / TOLE / TAZ",
        "DMC / TOLE / TOG",
        "DMC / TOLE / TPG",
        "DMC / TOLE / TPI",
        "DMC / TOLE / TPN / LARME",
        "DMC / TOLE / TPN / LC",
        "DMC / TOLE / TPN / LF",
        "DMC / TOLE / TRAPEZOIDALES",
        "DMC / TUBE / CARRE",
        "DMC / TUBE / RECTANGLE",
        "DMC / TUBE / ROND",
        "DMC / TUYAU"
    ],
    "MATÉRIEL ÉLECTRIQUE": [
        "ELC",
        "ELC / 45x45",
        "ELC / Accessoires /Divers",
        "ELC / Ampoules",
        "ELC / Appliques",
        "ELC / Armoire ARTU K/L/M",
        "ELC / Armoire IS2",
        "ELC / Armoire Type A",
        "ELC / Armoires Epower",
        "ELC / Attaches",
        "ELC / Automatisme",
        "ELC / Baie informatique",
        "ELC / Batterie de condensateur",
        "ELC / Batteries Stationnaires",
        "ELC / Batteries Stationnaires / LITHIUM",
        "ELC / Batteries Stationnaires / LITHIUM / ACCESSOIRES",
        "ELC / Boite Plexo/DCL/Divers",
        "ELC / Boites",
        "ELC / Bornes",
        "ELC / Bornes de Jonction",
        "ELC / Boutonnerie",
        "ELC / Câblage",
        "ELC / Câblage / Raccordement",
        "ELC / Câble Domestique",
        "ELC / Câble Indus Souple",
        "ELC / Câble Indus U1000AR2V",
        "ELC / Câble Indus U1000RO2V",
        "ELC / Cellule BB",
        "ELC / Chemin de Câble",
        "ELC / Coffret de Logement - Acc",
        "ELC / Coffret GEMINI/SR/EUROPA",
        "ELC / Coffrets/Accessoires",
        "ELC / Colonne",
        "ELC / Commande-Signal Module",
        "ELC / Comptage/TI",
        "ELC / Connecteurs",
        "ELC / Connectique",
        "ELC / Contacteur",
        "ELC / Contacteurs /Relais",
        "ELC / Contacteurs et Acc",
        "ELC / Cordons",
        "ELC / Coupe Circuit/Fusible",
        "ELC / Démarreur",
        "ELC / Detecteur Eclairage et Al",
        "ELC / Differentielle/Acc T Max",
        "ELC / Disjoncteur - Accessoires",
        "ELC / Disjoncteur Differenteil",
        "ELC / Disjoncteur E Max",
        "ELC / Disjoncteur Moteur",
        "ELC / Disjoncteur T Max",
        "ELC / Disjoncteurs à boitier",
        "ELC / Disjoncteurs Miniatures",
        "ELC / Divers",
        "ELC / Divers Cablage",
        "ELC / Divers mt",
        "ELC / Divers Produits ABB",
        "ELC / Divers Tout Produits",
        "ELC / ELECTRONIQUE DE PUISSANCE",
        "ELC / Etanche",
        "ELC / EV / CHARGEUR",
        "ELC / EV / E-BIKE",
        "ELC / EV / E-BIKE / Composants",
        "ELC / EV / KIT",
        "ELC / Exo Apparent",
        "ELC / Filière H07VR",
        "ELC / Filière HO7VK",
        "ELC / Gamme Fonte",
        "ELC / Goulotte",
        "ELC / Inter et Disjoncteur MT",
        "ELC / Interphones-Vidéophones",
        "ELC / Interrupteur",
        "ELC / Interrupteur différentei",
        "ELC / Interrupteur OT",
        "ELC / Interrupteur T Max",
        "ELC / Interrupteurs Différenti",
        "ELC / Interrupteurs sectionneu",
        "ELC / Jeu de Barre/ Repartiteur",
        "ELC / Lotissements",
        "ELC / Moulure",
        "ELC / Onduleurs Hybride OFF G",
        "ELC / Panneaux de Brassage",
        "ELC / Panneaux solaires",
        "ELC / Parafoudre",
        "ELC / Paratonnere",
        "ELC / Produits MT",
        "ELC / Produits Solaire",
        "ELC / Projecteurs",
        "ELC / Reglettes",
        "ELC / Régulateur de Tension",
        "ELC / Régulateurs Solaire",
        "ELC / Relais de Mesure/ Inter P",
        "ELC / Relais et Mesure",
        "ELC / Relais Logique",
        "ELC / Relais miniatures",
        "ELC / Relais Thermique",
        "ELC / Relais Thermiques",
        "ELC / Reseau MT",
        "ELC / S/Courant Faible",
        "ELC / Sécurité",
        "ELC / Série 21/22/27/CATALUNIA",
        "ELC / Série 75/82",
        "ELC / Services",
        "ELC / Spots",
        "ELC / Télécommande",
        "ELC / TPC/ICT/TUBE IRO",
        "ELC / Transfo ABB/NEXANS",
        "ELC / Transfo de Contrôle",
        "ELC / Transfo de courant",
        "ELC / Transformateur de courant",
        "ELC / Unité de commande et Bou",
        "ELC / UPS",
        "ELC / Variateur",
        "ELC / Ventilation",
        "ELC / Visserie et Cheville",
        "LAMPE",
        "AUTOMOTIVE / ELECTRICITE & APPAREILLAGES / VISIBILITE / AMPOULES ET DOUILLES"
    ],
    "ÉQUIPEMENTS & SYSTÈMES": [
        "ELC / GROUPE / Accessoires",
        "ELC / GROUPE / FILTRATION",
        "ELC / GROUPE DEUTZ / PDR",
        "ELC / GROUPE YUCHAI / PDR",
        "ELC / MOTOPOMPE",
        "ELC / FILTRATION",
        "ELC / FILTRATION / CARTOUCHES",
        "ELC / FILTRATION / TUBES",
        "ELC / OSMOSEURS",
        "ELC / OSMOSEURS / CARTOUCHES",
        "ELC / POMPES",
        "ELC / POMPES / ACCESSOIRES",
        "ELC / POMPES / CENTRIFUGES",
        "ELC / POMPES / KIT COMPLET",
        "ELC / SURPRESSEURS",
        "ELC / SURPRESSEURS / ACCESSOIRES",
        "ELC / SURPRESSEURS / CUVE",
        "ELC / TRAITEMENT-UV",
        "ELC / TRAITEMENT-UV / ACCESSOIRES",
        "Industrie / Poteaux",
    ],
    "PRODUITS CHIMIQUES": [
        "Industrie / Produits Chimiques / Additif alimentaire",
        "Industrie / Produits Chimiques / Base",
        "Industrie / Produits Chimiques / Composite",
        "Industrie / Produits Chimiques / Engrais",
        "Industrie / Produits Chimiques / Peinture",
        "Industrie / Produits Chimiques / Pesticide",
        "Industrie / Produits Chimiques / Traitement d'eau",
        "ELC / PEINTURE",
        "SAV Atelier / Peinture"
    ],
    "INDUSTRIE & DIVERS": [
        "Industrie",
        "Industrie / Autres",
        "Industrie / Conditionnements Emballages et Etiquettes",
        "Industrie / Déclassé",
        "Industrie / Equipements",
        "Industrie / Materiels Agricoles / Remorques",
        "Industrie / Pièces courantes",
        "Industrie / Pièces courantes / Autres",
        "Industrie / Pièces courantes / Courroie",
        "Industrie / Pièces courantes / Filtration",
        "Industrie / Pièces courantes / Roulement",
        "Industrie / Pièces industrielles",
        "Industrie / Transmission de puissance / Roulement",
        "ACC / PRODUIT",
        "ACC / PROMOTIONAL ITEMS",
        "ACC / Promotional Items",
        "ACC / SERVICE",
        "ACC / TVS",
        "ATP / Consommable",
        "AUTOMOTIVE / DECLASSER",
        "Autre / Riz",
        "DMC / DECLASSER",
        "Marchandises diverses",
        "PDR / SOLAIRE",
        "Poteau Jirama BA",
        "SAV Atelier"
    ],
    "IMMOBILIERS ou FOURNITURES": [
        "All / Comptabilité",
        "All / Fournitures / Autres",
        "All / Fournitures / Bureau",
        "All / HM",
        "All / Mobiliers",
    ],
    "HAVAMAD":[
        "All / HM",
    ],
    "Voiture":[
        "All / Parc",
    ]
}

lt = [
    'Bureau',
    'Mobiliers',
    'CHAISE',
    'armoire',
    'MATELAS RENO',
    'Fournitures / Bureau',
    'Accessoires autos',
    'Echappement',
    'radiateur',
    'disque frein',
    'amortisseur',
    'filtre',
    'Huile',
    'plaquette de frein',
    'Ressort',
    'Pneu',
    'roulement',
    'tip top',
    'Bougie',
    'carbutateur',
    'BOBINE',
    'BOBINE HAUTE VOLTAGE',
    'filtre a air',
    'PISTON',
    'FILTRE À HUILE',
    'PLAQUETTES DE FREIN',
    'VITRE PORTIERE',
    'PARE HUILE TRANSMISSION',
    'DISQUE',
    'jante',
    'EQUIPEMENT MOTO',
    'Pièces Motos',
    'Tôles ondulées',
    'bitume',
    'ciment',
    'buse',
    'carreaux',
    'fer',
    'tole',
    "OIL FILTER",
    'tube',
    'tuyau',
    'AVERTISSEUR',
    'MATÉRIEL ÉLECTRIQUE',
    'batterie',
    'Câble',
    ' ELECTRONIQUE DE PUISSANCE',
    'Interrupteur',
    'Disjoncteur',
    'Panneaux solaires',
    'Parafoudre',
    'Paratonnere',
    'Gravillon',
    "FIL ISOLE",
    "ADAPTATEUR",
    'Télécommande',
    'Ventilation',
    'LAMPE',
    'Spots',
    'Régulateur',
    'Relais Thermique',
    'Relais Logique',
    'Reglettes',
    'Projecteurs',
    'Produits Solaire',
    'Produits MT',
    'PRISE',
    'Prise',
    "DOUILLE",
    "PAREBRISE",
    "PARE BRISE",
    "CABLE ACCELERATEUR",
    "ENJOLIVEUR",
    "BOULON GALVANISE",
    'Panneaux de Brassage',
    'Onduleurs Hybride',
    'Moulure',
    'Jeu de Barre/ Repartiteur',
    'Interphones-Vidéophones',
    'Goulotte',
    'Filière H07VR',
    'CARTOUCHE',
    'Exo Apparent',
    'papier',
    'AMPOULE',
    "ATTACHE",
    'PILE',
    'VERNIS',
    "POIGNEE",
    "MOTO VENTILATEUR",
    "GLOBE AVG",
    "DISQUE D'EMBRAYAGE",
    "Acide",
    "VOLANT MOTEUR",
    "RETROVISEUR",
    "FEU",
    "CHAMBRE A AIR",
    "PNEU",
    "Reservoir",
    "CHASSIS ",
    "CABLE FREIN",
    'Démarreur',
    'Divers Cablage',
    'Disjoncteurs à boitier',
    'Disjoncteurs Miniatures',
    'Disjoncteur T Max',
    'Disjoncteur Differenteil',
    'Disjoncteur - Accessoires',
    'Differentielle',
    'Detecteur Eclairage',
    'Fusible',
    'Contacteurs et Acc',
    'Contacteur',
    'Comptage/TI',
    'Coffret',
    'Bornes de Jonction',
    'Boites',
    'Batteries',
    'Baie informatique',
    'Attaches',
    'Armoires Epower',
    'Armoire Type A',
    'Armoire ARTU K',
    'Ampoules',
    'Transformateur',
    'Compresseurs',
    'Outils',
    'Outillage',
    'ELECTROPORTATIFS',
    'elevateur',
    'Lubrifiants',
    'Additif alimentaire',
    'Base',
    'Composite',
    'Engrais',
    'Peinture',
    'Pesticide',
    "Tratement d'eau",
    'traitement-uv',
    'consommable',
    'SAVON',
    'CADENAS',
    'Marquaque',
    'BOUTON TOURNANT',
    'BOUTON POUSSOIR',
    'electrode',
    'bac',
    'Conditionnements Emballages et Etiquettes',
    'Visserie et Cheville',
    'PROMOTIONAL ITEMS',
    'Transmission de puissance',
    'groupe',
    'Extracteur Air',
    'GROUPES ELECTROGENE',
    'GROUPE YUCHAI',
    'Sécurité',
    'services',
    'service',
    'riz',
    'Lotissements',
    'Poteaux',
    'AUTO RADIO',
    "Bureau", "Mobiliers", "Chaise", "Fauteuil pivotant", "Fauteuil bureau", "Table de réunion", 
    "Armoire", "Armoire métallique", "Bibliothèque", "Casiers", "Classeurs", "Tiroirs", 
    "Lampes de bureau", "Accessoires bureau", "Fournitures / Bureau", "Bloc-notes", "Stylos",
    "Papiers A4", "Imprimante", "Cartouche encre", "Agrafeuse", "Perforatrice", "Tableau blanc",
    "Marqueurs", "Papeterie", "Classeur suspendu", "Cahier", "Agenda", "Étiquette autocollante",
    "Accessoires autos", "Échappement", "Radiateur moteur", "Disque frein", "Plaquettes de frein", 
    "Amortisseur", "Ressort", "Filtre huile", "Filtre air", "Huile moteur", "Pneu été", "Pneu hiver", 
    "Roulement", "Tip top", "Bougie", "Carburateur", "Batterie auto", "Jante alu", "Jante acier",
    "Clignotant avant", "Clignotant arrière", "Rétroviseur", "Pare-brise", "Feu arrière", "Feu avant", 
    "Volant moteur", "Démarreur", "Câble frein", "Porte-vitre", "Essuie-glace", "Bouchon réservoir",
    "Filtre carburant", "Filtre habitacle", "Courroie distribution", "Pompe à eau", "Alternateur",
    "Moteur complet", "Injecteur", "Capteur ABS", "Capteur température", "Capteur pression huile",
    "Équipement moto", "Pièces motos", "Casque moto", "Gants moto", "Kit chaîne", "Kit frein moto",
    "Huile moteur 2T", "Huile moteur 4T", "Batterie moto", "Clignotant moto", "Rétroviseur moto",
    "Pare-brise moto", "Disque embrayage", "Volant moteur moto", "Selle moto", "Poignée gaz",
    "Kit transmission", "Pneu moto", "Chaine moto", "Plaquette frein moto", "Suspension moto",
    "Matériel électrique", "Câble", "Fil isolé", "Adaptateur", "Interrupteur", "Disjoncteur", 
    "Panneaux solaires", "Parafoudre", "Paratonnerre", "Ventilation", "Lampe LED", "Spot encastrable",
    "Régulateur", "Relais thermique", "Relais logique", "Reglettes", "Projecteurs", "Produits solaire",
    "Prise électrique", "Douille", "Transformateur", "Boite de jonction", "Coffret électrique", "UPS",
    "Variateur", "Bornes", "Bornes de jonction", "Câble H07VR", "Câble HO7VK", "Cordons électriques",
    "Interrupteur différentiel", "Contacteur", "Contacteurs et relais", "Relais miniatures", "Onduleur",
    "Compteur électrique", "Éclairage LED", "Filtre secteur", "Électronique de puissance", "Composants EV",
    "Tôles ondulées", "Bitume", "Ciment", "Brique creuse", "Béton prêt", "Buse béton", "Carreaux", 
    "Fer", "Tube PVC", "Tube acier", "Tube carré", "Tube rectangle", "Tube rond", "Gravillon", "Tole",
    "Trapezoidales", "Poutrelle HEA", "Poutrelle IPE", "Poutrelle IPN", "UPN", "Gabion", "Geotextile",
    "Plâtre", "Enduit", "Mortier", "Parpaing", "Bardage", "Isolation thermique", "Isolation phonique",
    "Profil acier", "Profil aluminium", "Tôle galvanisée", "Visserie bâtiment", "Cheville", "Clous",
    "Compresseur", "Compresseur CP100L", "Compresseur CP150L", "Compresseur CP200L", "Électroportatif",
    "Perceuse", "Visseuse", "Scie circulaire", "Meuleuse", "Tournevis", "Clé à molette", "Marteau",
    "Niveau laser", "Clé dynamométrique", "Elevateur hydraulique", "Outils de mesure", "Outillage divers",
    "Pince", "Scie à métaux", "Lime", "Ciseaux", "Étau", "Ponceuse", "Compresseur atelier", "Pompe hydraulique",
    "Lubrifiants", "Huile moteur auto", "Graisse industrielle", "Additif alimentaire", "Peinture",
    "Pesticide", "Engrais", "Traitement eau", "Traitement UV", "Savon", "Base chimique", "Composite",
    "Décapant", "Solvant", "Diluant peinture", "Adhésif industriel", "Colle PVC", "Colle cyanoacrylate",
    "Conditionnements emballages", "Étiquettes", "Visserie et cheville", "Cadenas", "Promotional items",
    "Services", "Extracteur air", "Groupe électrogène", "Lotissements", "Poteaux", "Riz", "SAV atelier",
    "Sac plastique", "Film étirable", "Ruban adhésif", "Palette bois", "Palette plastique", "Conteneur",
    "Équipement sécurité", "Casque sécurité", "Gilet sécurité", "Chaussures sécurité", "Lunettes protection",
    "Véhicule CA", "VEH / Bus / Diesel", "VEH / Camion / Diesel", "VEH / Camion plateau / Diesel",
    "VEH / Remorque 13.5 m", "VEH / SUV", "Tracteur routier", "Véhicules occasions", "Camionnette",
    "Pickup", "Fourgon", "Minibus", "Tracteur agricole", "Engin TP", "Carrosserie", "Réservoir carburant",
    "Extincteur", "Détecteur fumée", "Détecteur gaz", "Trousse secours", "Barrière sécurité", "Signalisation",
    "Gilet haute visibilité", "Casque chantier", "Masque respiratoire", "Gants protection", "Chaussures sécurité",
    "Groupe filtration", "Motopompe", "Pompe centrifuge", "Pompe à eau", "Pompe surpresseur", 
    "Surpresseur cuve", "Accessoires pompe", "Filtration cartouche", "Filtration tube", "Osmoeurs",
    "Produits MT", "Produits Solaire", "Industrie", "Pièces courantes", "Transmission de puissance",
    "Roulement", "Extracteur air industriel", "GROUPES ELECTROGENE", "GROUPE YUCHAI", "Industrie / Equipements",

]