"""
Django settings for livraison project.

Generated by 'django-admin startproject' using Django 4.2.24.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta
import logging

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-h+!en^xz8iw9*t($yjok6v2mg3(_=(@jt+l79l&811mzut)b11")

# --- Google Cloud Platform Configuration ---
# This logic looks for GOOGLE_APPLICATION_CREDENTIALS in the environment variables (e.g., from .env) first.
# If not found, it falls back to looking for a key file named 'clé-viseo-env-prod-0afc5f090e0f.json'
# in the `backend` directory.
# If neither is found, the setting is None.

GCP_KEY_FILENAME = 'clé-viseo-env-prod-0afc5f090e0f.json'
key_path_from_env = os.getenv('GOOGLE_APPLICATION_CREDENTIALS')
fallback_key_path = BASE_DIR.parent / GCP_KEY_FILENAME

print(os.path.isfile(fallback_key_path))

if key_path_from_env and Path(key_path_from_env).is_file():
    GOOGLE_APPLICATION_CREDENTIALS = key_path_from_env
    logging.info(f"GCP credentials loaded from environment variable: {GOOGLE_APPLICATION_CREDENTIALS}")
elif fallback_key_path.is_file():
    GOOGLE_APPLICATION_CREDENTIALS = str(fallback_key_path)
    # Set the environment variable for Google SDKs that expect it.
    os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = GOOGLE_APPLICATION_CREDENTIALS
    logging.info(f"GCP credentials loaded from fallback path: {GOOGLE_APPLICATION_CREDENTIALS}")
else:
    GOOGLE_APPLICATION_CREDENTIALS = None
    logging.warning("GCP key file not found. Vertex AI features will be disabled.")

# GCP Project Configuration
GCP_PROJECT_ID = os.getenv('GCP_PROJECT_ID', 'viseo-env-prod')
GCP_LOCATION = os.getenv('GCP_LOCATION', 'us-central1')
# ----------------------------------------

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# In production, you should replace '*' with your actual domain names.
ALLOWED_HOSTS = ['10.68.163.2', '10.68.38.18', '10.68.38.17', 'livraison.erp', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'processing',
    'driver_vehicle',
    'dispatch_vehicule_article',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://10.68.163.2",
    "http://10.68.163.2:3000",
    "http://10.68.163.2:8081",
    "http://10.68.163.2:5173",
    "http://10.68.38.18:3000",
    "http://10.68.38.18:8081",
    "http://10.68.38.18:5173",
    "http://10.68.38.17:3000",
    "http://livraison.erp",
    "http://livraison.erp:3000",
    "http://localhost:3000",
    "http://localhost",
    "http://localhost:8081",
]

CSRF_TRUSTED_ORIGINS = [
    "http://10.68.163.2",
    "http://10.68.163.2:3000",
    "http://10.68.163.2:8081",
    "http://10.68.163.2:5173",
    "http://10.68.38.18:3000",
    "http://10.68.38.18:8081",
    "http://10.68.38.18:5173",
    "http://10.68.38.17:3000",
    "http://livraison.erp",
    "http://localhost:3000",
    "http://localhost",
]
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'livraison.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'livraison.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom API Configuration
API_URL = os.getenv("API_URL", "http://10.68.133.2:8000")
APP_ID = os.getenv("APP_ID","TDI_VISEO")
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Simple JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


SESSION_COOKIE_AGE = 1209600  # 2 semaines en secondes
SESSION_COOKIE_SECURE = False  # Mettez à True si vous utilisez HTTPS
SESSION_COOKIE_HTTPONLY = True

try:
    from .settings_local import *
except ImportError:
    pass